### ISSUE TITLE
Not supporting vtr file

### ISSUE THREAD

**Issue by huaweiping** [KIT-IBT/vtkToolbox#1]
Hi,

I download this project and compile the code. However, it seems not support ".vtr" file.

Error message:
```
Error using vtkRead
Unknown extension "vtr".
```

**Comment by steffenschuler** [comment]
As mentioned in the README, only datasets of type vtkPolyData or vtkUnstructuredGrid are supported, which are both represented as vtkPointSet (see also inheritance diagram at [https://vtk.org/doc/nightly/html/classvtkDataSet.html](https://vtk.org/doc/nightly/html/classvtkDataSet.html)).
vtkRectilinearGrid is unfortunately not supported at the moment.
