### ISSUE TITLE
Error using vtkread in matlab

### ISSUE THREAD

**Issue by ganiyatseun** [KIT-IBT/vtkToolbox#4]
Hello,
I keep having Matlab shutdown with the following error. I used to be able to use the addon by simply installing it and it didn't require any building using cmake which I am unsure how to do because I am unfamiliar with C++

MATLAB Log File: C:\Users\GANIY\AppData\Local\Temp\matlab_crash_dump.6084-1

------------------------------------------------
MATLAB Log File
------------------------------------------------ 

--------------------------------------------------------------------------------
             Access violation detected at 2024-05-15 18:03:39 -0500
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) Iris(R) Xe Graphics Version 31.0.101.5081 (2023-12-9)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 2359175
  MATLAB Root              : C:\Program Files\MATLAB\R2021a
  MATLAB Version           : 9.10.0.2198249 (R2021a) Update 8
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 11 Home
  Process ID               : 6084
  Processor ID             : x86 Family 6 Model 186 Stepping 3, GenuineIntel
  Session Key              : c21ca806-e740-45a0-8177-41bece3e22bb
  Window System            : Version 10.0 (Build 22631)

Fault Count: 1

Abnormal termination:
Access violation

Current Thread: 'MCR 0 interpreter thread' id 39356

Register State (from fault):
  RAX = 0000000000000000  RBX = 0000000000000001
  RCX = 000001bb1956fca0  RDX = 00007ffb0ac1acf8
  RSP = 0000007c893f5140  RBP = 0000007c893f5240
  RSI = 0000000000000001  RDI = 0000007c893f5fd0
 
   R8 = 0000000000000000   R9 = 0000000000000040
  R10 = 0000000000000340  R11 = 0000007c893f5100
  R12 = 0000007c893f5f00  R13 = 0000007c893f5500
  R14 = 000001bb2e53ffe0  R15 = 0000000000000001
 
  RIP = 00007ffaa76696c3  EFL = 00010256
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x00007ffaa76696c3 C:\Users\GANIY\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\vtkToolbox\MATLAB\vtkRead.mexw64+00038595 mexFunction+00000787
[  1] 0x00007ffadbc4eec9 C:\Program Files\MATLAB\R2021a\bin\win64\libmex.dll+00585417 mexfile::Inspector::needs_upgrade+00014585
[  2] 0x00007ffadbc4ffc2 C:\Program Files\MATLAB\R2021a\bin\win64\libmex.dll+00589762 MexRetrieveVersion+00003074
[  3] 0x00007ffadbc50137 C:\Program Files\MATLAB\R2021a\bin\win64\libmex.dll+00590135 MexRetrieveVersion+00003447
[  4] 0x00007ffadbc502e7 C:\Program Files\MATLAB\R2021a\bin\win64\libmex.dll+00590567 MexRetrieveVersion+00003879
[  5] 0x00007ffadbc30542 C:\Program Files\MATLAB\R2021a\bin\win64\libmex.dll+00460098 mexUnlock_800+00025874
[  6] 0x00007ffae3bcee80                     bin\win64\pgo\m_dispatcher.dll+00585344 Mfh_file::dispatch_file_common+00000164
[  7] 0x00007ffae3bce63e                     bin\win64\pgo\m_dispatcher.dll+00583230 Mfh_error::lookup+00003386
[  8] 0x00007ffae3bcedd5                     bin\win64\pgo\m_dispatcher.dll+00585173 Mfh_file::dispatch+00000045
[  9] 0x00007ffaa3996acd                            bin\win64\pgo\m_lxe.dll+00355021
[ 10] 0x00007ffaa399636f                            bin\win64\pgo\m_lxe.dll+00353135
[ 11] 0x00007ffaa3995ca1                            bin\win64\pgo\m_lxe.dll+00351393
[ 12] 0x00007ffaa39b23c7                            bin\win64\pgo\m_lxe.dll+00467911 MathWorks::lxe::initializeFcn+00106135
[ 13] 0x00007ffaa39b1261                            bin\win64\pgo\m_lxe.dll+00463457 MathWorks::lxe::initializeFcn+00101681
[ 14] 0x00007ffaa39b0c72                            bin\win64\pgo\m_lxe.dll+00461938 MathWorks::lxe::initializeFcn+00100162
[ 15] 0x00007ffaa39b53f3                            bin\win64\pgo\m_lxe.dll+00480243 MathWorks::lxe::initializeFcn+00118467
[ 16] 0x00007ffaa39b509f                            bin\win64\pgo\m_lxe.dll+00479391 MathWorks::lxe::initializeFcn+00117615
[ 17] 0x00007ffaa399d2c0                            bin\win64\pgo\m_lxe.dll+00381632 MathWorks::lxe::initializeFcn+00019856
[ 18] 0x00007ffaa399c0eb                            bin\win64\pgo\m_lxe.dll+00377067 MathWorks::lxe::initializeFcn+00015291
[ 19] 0x00007ffaa399b136                            bin\win64\pgo\m_lxe.dll+00373046 MathWorks::lxe::initializeFcn+00011270
[ 20] 0x00007ffaa3a74296                            bin\win64\pgo\m_lxe.dll+01262230 MathWorks::lxe::ShutdownLxeEngine+00031034
[ 21] 0x00007ffaa556f670                            bin\win64\pgo\m_lxe.dll+29554288 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00055824
[ 22] 0x00007ffaa556e5f4                            bin\win64\pgo\m_lxe.dll+29550068 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00051604
[ 23] 0x00007ffaa558b6fe                            bin\win64\pgo\m_lxe.dll+29669118 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00170654
[ 24] 0x00007ffaa55b9c5c                            bin\win64\pgo\m_lxe.dll+29858908 FeatureTestObservableWorkspace+00046096
[ 25] 0x00007ffa6353a550 C:\Program Files\MATLAB\R2021a\bin\win64\structuredoutput.dll+00370000 structuredoutput::changeDebuggerEnablement+00000512
[ 26] 0x00007ffa6353a976 C:\Program Files\MATLAB\R2021a\bin\win64\structuredoutput.dll+00371062 structuredoutput::liveEvaluateExport+00000358
[ 27] 0x00007ffb0a708bea C:\Program Files\MATLAB\R2021a\bin\win64\builtin.dll+00101354 MathWorks::builtin::BuiltinFcn::invoke+00001130
[ 28] 0x00007ffae3b64b9c                     bin\win64\pgo\m_dispatcher.dll+00150428 Mfh_MATLAB_fn_impl::dispatch_mf_with_reuse+00000136
[ 29] 0x00007ffae3b541d9                     bin\win64\pgo\m_dispatcher.dll+00082393 Mfh_MATLAB_fn_impl::ensure_loading_of_load_module+00000745
[ 30] 0x00007ffae3b52121                     bin\win64\pgo\m_dispatcher.dll+00074017 Mfh_MATLAB_fn_impl::dispatch+00000045
[ 31] 0x00007ffaa31705d6                        bin\win64\pgo\mcos_impl.dll+00525782 mdIsA+00171578
[ 32] 0x00007ffae3b48048                     bin\win64\pgo\m_dispatcher.dll+00032840 mdBuiltinAsBuiltinFcn+00000240
[ 33] 0x00007ffb0a708bea C:\Program Files\MATLAB\R2021a\bin\win64\builtin.dll+00101354 MathWorks::builtin::BuiltinFcn::invoke+00001130
[ 34] 0x00007ffae3b64b9c                     bin\win64\pgo\m_dispatcher.dll+00150428 Mfh_MATLAB_fn_impl::dispatch_mf_with_reuse+00000136
[ 35] 0x00007ffae3b53588                     bin\win64\pgo\m_dispatcher.dll+00079240 Mfh_MATLAB_fn_impl::dispatch+00000712
[ 36] 0x00007ffae3b532ed                     bin\win64\pgo\m_dispatcher.dll+00078573 Mfh_MATLAB_fn_impl::dispatch+00000045
[ 37] 0x00007ffaa3997115                            bin\win64\pgo\m_lxe.dll+00356629
[ 38] 0x00007ffaa39e4ede                            bin\win64\pgo\m_lxe.dll+00675550 MathWorks::lxe::initializeFcn+00313774
[ 39] 0x00007ffaa399636f                            bin\win64\pgo\m_lxe.dll+00353135
[ 40] 0x00007ffaa3994431                            bin\win64\pgo\m_lxe.dll+00345137
[ 41] 0x00007ffaa39b23c7                            bin\win64\pgo\m_lxe.dll+00467911 MathWorks::lxe::initializeFcn+00106135
[ 42] 0x00007ffaa39b1261                            bin\win64\pgo\m_lxe.dll+00463457 MathWorks::lxe::initializeFcn+00101681
[ 43] 0x00007ffaa39b0c72                            bin\win64\pgo\m_lxe.dll+00461938 MathWorks::lxe::initializeFcn+00100162
[ 44] 0x00007ffaa39b53f3                            bin\win64\pgo\m_lxe.dll+00480243 MathWorks::lxe::initializeFcn+00118467
[ 45] 0x00007ffaa39b509f                            bin\win64\pgo\m_lxe.dll+00479391 MathWorks::lxe::initializeFcn+00117615
[ 46] 0x00007ffaa399d2c0                            bin\win64\pgo\m_lxe.dll+00381632 MathWorks::lxe::initializeFcn+00019856
[ 47] 0x00007ffaa399c0eb                            bin\win64\pgo\m_lxe.dll+00377067 MathWorks::lxe::initializeFcn+00015291
[ 48] 0x00007ffaa399b136                            bin\win64\pgo\m_lxe.dll+00373046 MathWorks::lxe::initializeFcn+00011270
[ 49] 0x00007ffaa3a11667                            bin\win64\pgo\m_lxe.dll+00857703 MathWorks::lxe::initializeFcn+00495927
[ 50] 0x00007ffaa39983fa                            bin\win64\pgo\m_lxe.dll+00361466
[ 51] 0x00007ffaa3b018c5                            bin\win64\pgo\m_lxe.dll+01841349 mwboost::archive::detail::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>+00045473
[ 52] 0x00007ffae3b549f8                     bin\win64\pgo\m_dispatcher.dll+00084472 Mfh_MATLAB_fn_impl::need_FunctionExecutionFrame+00000568
[ 53] 0x00007ffae3b55f0d                     bin\win64\pgo\m_dispatcher.dll+00089869 Mfh_file::dispatch+00000045
[ 54] 0x00007ffaa3149a44                        bin\win64\pgo\mcos_impl.dll+00367172 mdIsA+00012968
[ 55] 0x00007ffaa314b267                        bin\win64\pgo\mcos_impl.dll+00373351 mdIsA+00019147
[ 56] 0x00007ffaa3143336                        bin\win64\pgo\mcos_impl.dll+00340790
[ 57] 0x00007ffaa3142da0                        bin\win64\pgo\mcos_impl.dll+00339360
[ 58] 0x00007ffaa318c9bb                        bin\win64\pgo\mcos_impl.dll+00641467 mdMethodListAllFcn+00085739
[ 59] 0x00007ffaa318c8d0                        bin\win64\pgo\mcos_impl.dll+00641232 mdMethodListAllFcn+00085504
[ 60] 0x00007ffaa318c800                        bin\win64\pgo\mcos_impl.dll+00641024 mdMethodListAllFcn+00085296
[ 61] 0x00007ffaa3146f7d                        bin\win64\pgo\mcos_impl.dll+00356221 mdIsA+00002017
[ 62] 0x00007ffae3b54630                     bin\win64\pgo\m_dispatcher.dll+00083504 Mfh_MATLAB_fn_impl::ensure_loading_of_load_module+00001856
[ 63] 0x00007ffae3b547b9                     bin\win64\pgo\m_dispatcher.dll+00083897 Mfh_MATLAB_fn_impl::dispatch_with_reuse+00000045
[ 64] 0x00007ffaa3997e2e                            bin\win64\pgo\m_lxe.dll+00359982
[ 65] 0x00007ffaa3993c2e                            bin\win64\pgo\m_lxe.dll+00343086
[ 66] 0x00007ffaa3a71de2                            bin\win64\pgo\m_lxe.dll+01252834 MathWorks::lxe::ShutdownLxeEngine+00021638
[ 67] 0x00007ffaa3a71c8e                            bin\win64\pgo\m_lxe.dll+01252494 MathWorks::lxe::ShutdownLxeEngine+00021298
[ 68] 0x00007ffaa3b3f3e2                            bin\win64\pgo\m_lxe.dll+02094050 mwboost::archive::detail::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>+00298174
[ 69] 0x00007ffaa3b3f348                            bin\win64\pgo\m_lxe.dll+02093896 mwboost::archive::detail::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>::oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::ClosedAbstractionFunctionDescriptorOwningIrTree>+00298020
[ 70] 0x00007ffae0ea5cde                    bin\win64\pgo\m_interpreter.dll+00089310 inCallFcnWithTrapInDesiredWSAndPublishEvents+00000098
[ 71] 0x00007ffae1a4ee12   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00716306 iqm::BaseFEvalPlugin::inCallFcnWithTrap+00000066
[ 72] 0x00007ffae1a4e6c7   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00714439 iqm::BaseFEvalPlugin::execute+00000455
[ 73] 0x00007ffae1a4e4e2   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00713954 iqm::FEvalPlugin<cmddistributor::FEvalIIP>::execute+00000018
[ 74] 0x00007ffadec2df1d   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00515869 services::lmgr::exception::LicensingStartupException::~LicensingStartupException+00008893
[ 75] 0x00007ffae1a58883   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00755843 iqm::DelegateToAnotherIqmPlugin::execute+00000019
[ 76] 0x00007ffabf00c406   C:\Program Files\MATLAB\R2021a\bin\win64\jmi.dll+00705542 LoadJAWTLibrary+00009110
[ 77] 0x00007ffae1a366ac   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00616108 iqm::Iqm::setupIqmFcnPtrs+00106204
[ 78] 0x00007ffae1a071f0   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00422384 iqm::Iqm::create+00007024
[ 79] 0x00007ffb0ae98eaf C:\Program Files\MATLAB\R2021a\bin\win64\libmwbridge.dll+00102063 ioReadLine+00000463
[ 80] 0x00007ffb0ae98ca5 C:\Program Files\MATLAB\R2021a\bin\win64\libmwbridge.dll+00101541 ioReadLine+00000165
[ 81] 0x00007ffb0aeaa761 C:\Program Files\MATLAB\R2021a\bin\win64\libmwbridge.dll+00173921 mnGetCommandLineBuffer+00000289
[ 82] 0x00007ffb0aeaabb7 C:\Program Files\MATLAB\R2021a\bin\win64\libmwbridge.dll+00175031 mnParser+00000487
[ 83] 0x00007ffadec33d86   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00540038 mcr_set_enableReadingFromStdin+00013894
[ 84] 0x00007ffadebcf5d3   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00128467 mcrFunctionSignature::set_signature+00107555
[ 85] 0x00007ffadebeb550   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00243024 mcrFunctionSignature::set_signature+00222112
[ 86] 0x00007ffae1a639ea   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00801258 iqm::PackagedTaskPlugin::execute+00000074
[ 87] 0x00007ffadec2e1ed   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00516589 services::lmgr::exception::LicensingStartupException::~LicensingStartupException+00009613
[ 88] 0x00007ffae1a366ac   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00616108 iqm::Iqm::setupIqmFcnPtrs+00106204
[ 89] 0x00007ffae1a084bc   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00427196 iqm::Iqm::create+00011836
[ 90] 0x00007ffae1a07c32   C:\Program Files\MATLAB\R2021a\bin\win64\iqm.dll+00425010 iqm::Iqm::create+00009650
[ 91] 0x00007ffadec058fc   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00350460 mcrInstantiationError::operator=+00010428
[ 92] 0x00007ffadec064ac   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00353452 mcrInstantiationError::operator=+00013420
[ 93] 0x00007ffadec03ac0   C:\Program Files\MATLAB\R2021a\bin\win64\mcr.dll+00342720 mcrInstantiationError::operator=+00002688
[ 94] 0x00007ffb32ec9b9a C:\Program Files\MATLAB\R2021a\bin\win64\mwboost_thread-vc142-mt-x64-1_72.dll+00039834 mwboost::thread::swap+00000074
[ 95] 0x00007ffb77f69333                   C:\Windows\System32\ucrtbase.dll+00168755 recalloc+00000163
[ 96] 0x00007ffb7968257d                   C:\Windows\System32\KERNEL32.DLL+00075133 BaseThreadInitThunk+00000029
[ 97] 0x00007ffb7a82aa48                      C:\Windows\SYSTEM32\ntdll.dll+00371272 RtlUserThreadStart+00000040

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

**Comment by axel-loewe** [comment]
You will need to compile the mex files for your architecture as described in the README
